BEGIN;

CREATE TABLE comments (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    post_id VARCHAR(32) NOT NULL,
    content_internal_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    root_id BIGINT NULL,
    parent_id BIGINT NULL,
    content TEXT NULL,
    image_file_ids TEXT[] NULL,
    voice_file_id TEXT NULL,
    voice_duration INTEGER NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'NORMAL',
    deleted_by BIGINT NULL,
    deleted_by_role VARCHAR(32) NULL,
    delete_reason VARCHAR(500) NULL,
    deleted_at TIMESTAMPTZ NULL,
    edited_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (status IN ('NORMAL', 'DELETED')),
    CHECK (deleted_by_role IS NULL OR deleted_by_role IN ('AUTHOR', 'ADMIN')),
    CHECK (
        (root_id IS NULL AND parent_id IS NULL)
        OR (root_id IS NOT NULL AND parent_id IS NOT NULL)
    ),
    CHECK (
        (root_id IS NULL OR root_id <> id)
        AND (parent_id IS NULL OR parent_id <> id)
    ),
    CHECK (
        (content IS NOT NULL AND btrim(content) <> '')
        OR COALESCE(cardinality(image_file_ids), 0) > 0
        OR (voice_file_id IS NOT NULL AND btrim(voice_file_id) <> '')
    ),
    CHECK (COALESCE(cardinality(image_file_ids), 0) <= 9),
    CHECK (voice_file_id IS NULL OR COALESCE(cardinality(image_file_ids), 0) = 0),
    CHECK (
        (voice_file_id IS NULL AND voice_duration IS NULL)
        OR (voice_file_id IS NOT NULL AND voice_duration > 0)
    )
);

CREATE INDEX ix_comments_post_top_time
    ON comments (post_id, id DESC)
    WHERE root_id IS NULL AND parent_id IS NULL AND status = 'NORMAL';

CREATE INDEX ix_comments_root_replies_time
    ON comments (root_id, id ASC)
    WHERE status = 'NORMAL';

CREATE INDEX ix_comments_parent_id
    ON comments (parent_id)
    WHERE parent_id IS NOT NULL;

CREATE TABLE comment_stats (
    comment_id BIGINT PRIMARY KEY REFERENCES comments (id),
    like_count BIGINT NOT NULL DEFAULT 0,
    reply_count BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (like_count >= 0),
    CHECK (reply_count >= 0)
);

CREATE TABLE comment_post_stats (
    post_id VARCHAR(32) PRIMARY KEY,
    total_comments BIGINT NOT NULL DEFAULT 0,
    total_top_level_comments BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (total_comments >= 0),
    CHECK (total_top_level_comments >= 0),
    CHECK (total_top_level_comments <= total_comments)
);

CREATE TABLE comment_likes (
    comment_id BIGINT NOT NULL REFERENCES comments (id),
    user_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (comment_id, user_id)
);

CREATE TABLE comment_counter_deltas (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    comment_id BIGINT NOT NULL REFERENCES comments (id),
    post_id VARCHAR(32) NOT NULL,
    counter_type VARCHAR(32) NOT NULL,
    delta_value INTEGER NOT NULL,
    source_event_id VARCHAR(64) NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    claimed_by VARCHAR(128) NULL,
    claimed_at TIMESTAMPTZ NULL,
    processed_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (counter_type IN ('LIKE')),
    CHECK (delta_value IN (-1, 1)),
    CHECK (status IN ('PENDING', 'PROCESSING', 'DONE', 'FAILED'))
);

CREATE INDEX ix_comment_counter_deltas_pending
    ON comment_counter_deltas (status, id)
    WHERE status IN ('PENDING', 'FAILED');

CREATE TABLE comment_hot_rank (
    comment_id BIGINT PRIMARY KEY REFERENCES comments (id),
    post_id VARCHAR(32) NOT NULL,
    like_count BIGINT NOT NULL DEFAULT 0,
    visible BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (like_count >= 0)
);

CREATE INDEX ix_comment_hot_rank_post_hot
    ON comment_hot_rank (post_id, like_count DESC, comment_id ASC)
    WHERE visible = TRUE;

CREATE TABLE comment_recommended_rank (
    comment_id BIGINT PRIMARY KEY REFERENCES comments (id),
    post_id VARCHAR(32) NOT NULL,
    like_count BIGINT NOT NULL DEFAULT 0,
    freshness_tier VARCHAR(32) NOT NULL,
    recommended_score BIGINT NOT NULL DEFAULT 0,
    next_decay_at TIMESTAMPTZ NULL,
    visible BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (like_count >= 0)
);

CREATE INDEX ix_comment_recommended_rank_post
    ON comment_recommended_rank (post_id, recommended_score DESC, comment_id DESC)
    WHERE visible = TRUE;

CREATE INDEX ix_comment_recommended_rank_decay
    ON comment_recommended_rank (next_decay_at)
    WHERE visible = TRUE AND next_decay_at IS NOT NULL;

CREATE TABLE outbox_events (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    event_id VARCHAR(64) NOT NULL UNIQUE,
    event_type VARCHAR(128) NOT NULL,
    payload_version INT NOT NULL DEFAULT 1,
    aggregate_type VARCHAR(64) NOT NULL,
    aggregate_id VARCHAR(64) NOT NULL,
    payload_json JSONB NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    claimed_by VARCHAR(128) NULL,
    claim_started_at TIMESTAMPTZ NULL,
    attempt_count INT NOT NULL DEFAULT 0,
    next_retry_at TIMESTAMPTZ NULL,
    last_error TEXT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at TIMESTAMPTZ NULL,
    CHECK (payload_version > 0),
    CHECK (status IN ('PENDING', 'CLAIMING', 'PUBLISHED', 'FAILED', 'DEAD')),
    CHECK (status = 'CLAIMING' OR (claimed_by IS NULL AND claim_started_at IS NULL)),
    CHECK (status <> 'CLAIMING' OR (claimed_by IS NOT NULL AND claim_started_at IS NOT NULL)),
    CHECK (attempt_count >= 0),
    CHECK (published_at IS NULL OR published_at >= occurred_at)
);

CREATE INDEX ix_outbox_events_status_next_retry_at_id
    ON outbox_events (status, next_retry_at, id);

CREATE INDEX ix_outbox_events_claim_started_at
    ON outbox_events (claim_started_at)
    WHERE status = 'CLAIMING';

CREATE INDEX ix_outbox_events_aggregate_occurred_at
    ON outbox_events (aggregate_type, aggregate_id, occurred_at);

COMMIT;
