BEGIN;

CREATE TABLE scheduled_publish_events (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    post_id BIGINT NOT NULL REFERENCES posts (id),
    public_id VARCHAR(64) NOT NULL,
    owner_id BIGINT NOT NULL,
    draft_body_id VARCHAR(64) NOT NULL,
    draft_body_hash VARCHAR(80) NOT NULL,
    scheduled_at TIMESTAMPTZ NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    attempt_count INT NOT NULL DEFAULT 0,
    last_error TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    claimed_by VARCHAR(128) NULL,
    claimed_at TIMESTAMPTZ NULL,
    canceled_at TIMESTAMPTZ NULL,
    executed_at TIMESTAMPTZ NULL,
    CHECK (public_id <> ''),
    CHECK (draft_body_id <> ''),
    CHECK (draft_body_hash <> ''),
    CHECK (scheduled_at > created_at),
    CHECK (status IN ('PENDING', 'CANCELED', 'EXECUTED', 'FAILED', 'DEAD')),
    CHECK (attempt_count >= 0)
);

CREATE UNIQUE INDEX ux_scheduled_publish_events_pending_post
    ON scheduled_publish_events (post_id)
    WHERE status = 'PENDING';

CREATE INDEX ix_scheduled_publish_events_due
    ON scheduled_publish_events (scheduled_at, id)
    WHERE status = 'PENDING';

COMMIT;
