BEGIN;

CREATE TABLE post_likes (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    post_id BIGINT NOT NULL REFERENCES posts (id),
    user_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (post_id, user_id),
    CHECK (user_id > 0)
);

CREATE INDEX ix_post_likes_user_post
    ON post_likes (user_id, post_id);

CREATE TABLE post_favorites (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    post_id BIGINT NOT NULL REFERENCES posts (id),
    user_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (user_id > 0)
);

CREATE UNIQUE INDEX ux_post_favorites_post_user
    ON post_favorites (post_id, user_id);

CREATE INDEX ix_post_favorites_user_post
    ON post_favorites (user_id, post_id);

COMMIT;
