BEGIN;

CREATE TABLE admin_post_audit (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    post_id BIGINT NOT NULL REFERENCES posts (id),
    public_id VARCHAR(64) NOT NULL,
    admin_user_id BIGINT NOT NULL,
    action VARCHAR(32) NOT NULL,
    reason TEXT NOT NULL,
    previous_status VARCHAR(32) NOT NULL,
    new_status VARCHAR(32) NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (public_id <> ''),
    CHECK (admin_user_id > 0),
    CHECK (action IN ('DELETE')),
    CHECK (btrim(reason) <> ''),
    CHECK (previous_status IN ('DRAFT', 'PUBLISHED', 'SCHEDULED', 'DELETED')),
    CHECK (new_status IN ('DRAFT', 'PUBLISHED', 'SCHEDULED', 'DELETED'))
);

CREATE INDEX ix_admin_post_audit_post_created_at
    ON admin_post_audit (post_id, created_at DESC);

CREATE INDEX ix_admin_post_audit_admin_created_at
    ON admin_post_audit (admin_user_id, created_at DESC);

CREATE INDEX ix_admin_post_audit_public_id_created_at
    ON admin_post_audit (public_id, created_at DESC);

COMMIT;
