BEGIN;

CREATE TABLE posts (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    public_id VARCHAR(64) NOT NULL,
    owner_id BIGINT NOT NULL,
    owner_display_name VARCHAR(128) NOT NULL DEFAULT '',
    owner_avatar_file_id VARCHAR(128) NULL,
    owner_profile_version BIGINT NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    post_version BIGINT NOT NULL DEFAULT 1,
    published_title VARCHAR(200) NULL,
    published_summary VARCHAR(500) NULL,
    published_cover_file_id VARCHAR(128) NULL,
    published_body_id VARCHAR(64) NULL,
    published_body_hash VARCHAR(80) NULL,
    published_plain_text_length INT NULL,
    published_at TIMESTAMPTZ NULL,
    draft_title VARCHAR(200) NULL,
    draft_summary VARCHAR(500) NULL,
    draft_cover_file_id VARCHAR(128) NULL,
    draft_body_id VARCHAR(64) NULL,
    draft_body_hash VARCHAR(80) NULL,
    draft_size_bytes INT NULL,
    draft_plain_text_length INT NULL,
    deleted_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (public_id <> ''),
    CHECK (owner_profile_version >= 0),
    CHECK (post_version > 0),
    CHECK (status IN ('DRAFT', 'PUBLISHED', 'SCHEDULED', 'DELETED')),
    CHECK (published_plain_text_length IS NULL OR published_plain_text_length >= 0),
    CHECK (draft_size_bytes IS NULL OR draft_size_bytes >= 0),
    CHECK (draft_plain_text_length IS NULL OR draft_plain_text_length >= 0),
    CHECK (
        status <> 'PUBLISHED'
        OR (
            published_title IS NOT NULL
            AND btrim(published_title) <> ''
            AND published_body_id IS NOT NULL
            AND published_body_hash IS NOT NULL
            AND published_plain_text_length IS NOT NULL
            AND published_at IS NOT NULL
        )
    )
);

CREATE UNIQUE INDEX ux_posts_public_id
    ON posts (public_id);

CREATE INDEX ix_posts_owner_status_updated_at
    ON posts (owner_id, status, updated_at DESC, id DESC);

CREATE INDEX ix_posts_published_at
    ON posts (published_at DESC, id DESC)
    WHERE status = 'PUBLISHED';

CREATE INDEX ix_posts_draft_body_id
    ON posts (draft_body_id)
    WHERE draft_body_id IS NOT NULL;

CREATE INDEX ix_posts_published_body_id
    ON posts (published_body_id)
    WHERE published_body_id IS NOT NULL;

CREATE TABLE post_stats (
    post_id BIGINT PRIMARY KEY REFERENCES posts (id),
    view_count BIGINT NOT NULL DEFAULT 0,
    like_count BIGINT NOT NULL DEFAULT 0,
    favorite_count BIGINT NOT NULL DEFAULT 0,
    comment_count BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (view_count >= 0),
    CHECK (like_count >= 0),
    CHECK (favorite_count >= 0),
    CHECK (comment_count >= 0)
);

CREATE TABLE outbox_events (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    event_id VARCHAR(64) NOT NULL UNIQUE,
    event_type VARCHAR(128) NOT NULL,
    payload_version INT NOT NULL DEFAULT 1,
    aggregate_type VARCHAR(64) NOT NULL,
    aggregate_id VARCHAR(64) NOT NULL,
    aggregate_version BIGINT NULL,
    payload_json JSONB NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    claimed_by VARCHAR(128) NULL,
    claim_started_at TIMESTAMPTZ NULL,
    attempt_count INT NOT NULL DEFAULT 0,
    next_retry_at TIMESTAMPTZ NULL,
    last_error TEXT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at TIMESTAMPTZ NULL,
    CHECK (payload_version > 0),
    CHECK (status IN ('PENDING', 'CLAIMING', 'PUBLISHED', 'FAILED', 'DEAD')),
    CHECK (status = 'CLAIMING' OR (claimed_by IS NULL AND claim_started_at IS NULL)),
    CHECK (status <> 'CLAIMING' OR (claimed_by IS NOT NULL AND claim_started_at IS NOT NULL)),
    CHECK (attempt_count >= 0),
    CHECK (published_at IS NULL OR published_at >= occurred_at)
);

CREATE INDEX ix_outbox_events_status_next_retry_at_id
    ON outbox_events (status, next_retry_at, id);

CREATE INDEX ix_outbox_events_claim_started_at
    ON outbox_events (claim_started_at)
    WHERE status = 'CLAIMING';

CREATE INDEX ix_outbox_events_aggregate_occurred_at
    ON outbox_events (aggregate_type, aggregate_id, occurred_at);

CREATE TABLE domain_event_tasks (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    task_id VARCHAR(64) NOT NULL UNIQUE,
    event_type VARCHAR(128) NOT NULL,
    aggregate_type VARCHAR(64) NOT NULL,
    aggregate_id VARCHAR(64) NOT NULL,
    priority INT NOT NULL DEFAULT 0,
    payload_json JSONB NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    claimed_by VARCHAR(128) NULL,
    claimed_at TIMESTAMPTZ NULL,
    attempt_count INT NOT NULL DEFAULT 0,
    next_retry_at TIMESTAMPTZ NULL,
    last_error TEXT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMPTZ NULL,
    CHECK (priority >= 0),
    CHECK (status IN ('PENDING', 'PROCESSING', 'DONE', 'FAILED', 'DEAD')),
    CHECK (attempt_count >= 0)
);

CREATE INDEX ix_domain_event_tasks_status_next_retry_at_id
    ON domain_event_tasks (status, next_retry_at, id);

CREATE INDEX ix_domain_event_tasks_aggregate_occurred_at
    ON domain_event_tasks (aggregate_type, aggregate_id, occurred_at);

CREATE TABLE content_body_cleanup_tasks (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    post_id BIGINT NULL REFERENCES posts (id),
    body_id VARCHAR(64) NOT NULL,
    task_type VARCHAR(32) NOT NULL,
    reason VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    claimed_by VARCHAR(128) NULL,
    claimed_at TIMESTAMPTZ NULL,
    attempt_count INT NOT NULL DEFAULT 0,
    next_retry_at TIMESTAMPTZ NULL,
    last_error TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMPTZ NULL,
    UNIQUE (body_id, task_type),
    CHECK (body_id <> ''),
    CHECK (task_type IN ('OLD_DRAFT', 'OLD_SNAPSHOT', 'ORPHAN_DRAFT', 'ORPHAN_SNAPSHOT')),
    CHECK (reason IN ('draft_replaced', 'post_published', 'publish_tx_failed', 'manual_repair')),
    CHECK (status IN ('PENDING', 'PROCESSING', 'DONE', 'FAILED', 'DEAD')),
    CHECK (attempt_count >= 0)
);

CREATE INDEX ix_content_body_cleanup_tasks_status_next_retry_at_id
    ON content_body_cleanup_tasks (status, next_retry_at, id);

CREATE INDEX ix_content_body_cleanup_tasks_post_id
    ON content_body_cleanup_tasks (post_id)
    WHERE post_id IS NOT NULL;

CREATE TABLE content_body_repair_tasks (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    post_id BIGINT NOT NULL REFERENCES posts (id),
    body_id VARCHAR(64) NOT NULL,
    task_type VARCHAR(64) NOT NULL,
    expected_hash VARCHAR(80) NULL,
    observed_hash VARCHAR(80) NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    claimed_by VARCHAR(128) NULL,
    claimed_at TIMESTAMPTZ NULL,
    attempt_count INT NOT NULL DEFAULT 0,
    next_retry_at TIMESTAMPTZ NULL,
    last_error TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMPTZ NULL,
    UNIQUE (post_id, task_type, body_id),
    CHECK (body_id <> ''),
    CHECK (task_type IN ('published_body_missing', 'draft_body_missing', 'body_hash_mismatch', 'mongo_read_error_after_pg_published')),
    CHECK (status IN ('PENDING', 'PROCESSING', 'DONE', 'FAILED', 'DEAD')),
    CHECK (attempt_count >= 0)
);

CREATE INDEX ix_content_body_repair_tasks_status_next_retry_at_id
    ON content_body_repair_tasks (status, next_retry_at, id);

CREATE INDEX ix_content_body_repair_tasks_post_id
    ON content_body_repair_tasks (post_id);

COMMIT;
