BEGIN;

ALTER TABLE posts ADD COLUMN category_id BIGINT NULL;
ALTER TABLE posts ADD COLUMN topic_id BIGINT NULL;

CREATE TABLE categories (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    kind VARCHAR(16) NOT NULL,
    public_id VARCHAR(64) NOT NULL,
    slug VARCHAR(96) NOT NULL,
    name VARCHAR(128) NOT NULL,
    description VARCHAR(500) NOT NULL DEFAULT '',
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (kind IN ('CATEGORY', 'TOPIC')),
    CHECK (public_id <> ''),
    CHECK (slug <> ''),
    CHECK (name <> ''),
    CHECK (status IN ('ACTIVE', 'DISABLED'))
);

CREATE UNIQUE INDEX ux_categories_public_id
    ON categories (public_id);

CREATE UNIQUE INDEX ux_categories_kind_slug
    ON categories (kind, slug);

CREATE INDEX ix_categories_kind_status_slug
    ON categories (kind, status, slug, id);

ALTER TABLE posts
    ADD CONSTRAINT fk_posts_category_id
    FOREIGN KEY (category_id) REFERENCES categories (id);

ALTER TABLE posts
    ADD CONSTRAINT fk_posts_topic_id
    FOREIGN KEY (topic_id) REFERENCES categories (id);

CREATE INDEX ix_posts_category_published_at
    ON posts (category_id, published_at DESC, id DESC)
    WHERE category_id IS NOT NULL AND status = 'PUBLISHED';

CREATE INDEX ix_posts_topic_published_at
    ON posts (topic_id, published_at DESC, id DESC)
    WHERE topic_id IS NOT NULL AND status = 'PUBLISHED';

CREATE TABLE tags (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    public_id VARCHAR(64) NOT NULL,
    slug VARCHAR(96) NOT NULL,
    name VARCHAR(128) NOT NULL,
    description VARCHAR(500) NOT NULL DEFAULT '',
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (public_id <> ''),
    CHECK (slug <> ''),
    CHECK (name <> ''),
    CHECK (status IN ('ACTIVE', 'DISABLED'))
);

CREATE UNIQUE INDEX ux_tags_public_id
    ON tags (public_id);

CREATE UNIQUE INDEX ux_tags_slug
    ON tags (slug);

CREATE INDEX ix_tags_status_slug_id
    ON tags (status, slug, id);

CREATE TABLE tag_stats (
    tag_id BIGINT PRIMARY KEY REFERENCES tags (id) ON DELETE CASCADE,
    post_count BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (post_count >= 0)
);

CREATE INDEX ix_tag_stats_hot
    ON tag_stats (post_count DESC, tag_id)
    WHERE post_count > 0;

CREATE TABLE post_tags (
    post_id BIGINT NOT NULL REFERENCES posts (id) ON DELETE CASCADE,
    tag_id BIGINT NOT NULL REFERENCES tags (id),
    position INT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (post_id, position),
    CHECK (position >= 0)
);

CREATE UNIQUE INDEX ux_post_tags_post_tag
    ON post_tags (post_id, tag_id);

CREATE INDEX ix_post_tags_tag_post
    ON post_tags (tag_id, post_id);

COMMIT;
