BEGIN;

CREATE TABLE users (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    public_id VARCHAR(64) NOT NULL,
    account_id BIGINT NOT NULL,
    nickname VARCHAR(15) NOT NULL,
    avatar_file_id VARCHAR(128) NULL,
    bio VARCHAR(100) NOT NULL DEFAULT '',
    stranger_message_allowed BOOLEAN NOT NULL DEFAULT TRUE,
    user_status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    profile_version BIGINT NOT NULL DEFAULT 0,
    deleted_reason VARCHAR(255) NULL,
    deleted_by BIGINT NULL,
    deleted_at TIMESTAMPTZ NULL,
    restored_reason VARCHAR(255) NULL,
    restored_by BIGINT NULL,
    restored_at TIMESTAMPTZ NULL,
    deactivated_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (profile_version >= 0),
    CHECK (public_id <> ''),
    CHECK (nickname <> ''),
    CHECK (user_status IN ('ACTIVE', 'DEACTIVATED', 'DELETED')),
    CHECK (deleted_at IS NULL OR deleted_by IS NOT NULL),
    CHECK (restored_at IS NULL OR restored_by IS NOT NULL)
);

CREATE UNIQUE INDEX ux_users_public_id
    ON users (public_id);

CREATE UNIQUE INDEX ux_users_account_id
    ON users (account_id);

CREATE UNIQUE INDEX ux_users_nickname
    ON users (nickname);

CREATE INDEX ix_users_status
    ON users (user_status);

CREATE TABLE user_follows (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    follower_id BIGINT NOT NULL,
    following_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (follower_id, following_id),
    CHECK (follower_id <> following_id)
);

CREATE INDEX ix_user_follows_follower_id_desc
    ON user_follows (follower_id, id DESC);

CREATE INDEX ix_user_follows_following_id_desc
    ON user_follows (following_id, id DESC);

CREATE TABLE user_follow_stats (
    user_id BIGINT PRIMARY KEY,
    followers_count BIGINT NOT NULL DEFAULT 0,
    following_count BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (followers_count >= 0),
    CHECK (following_count >= 0)
);

CREATE TABLE user_blocks (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    blocker_id BIGINT NOT NULL,
    blocked_id BIGINT NOT NULL,
    reason VARCHAR(255) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (blocker_id, blocked_id),
    CHECK (blocker_id <> blocked_id)
);

CREATE INDEX ix_user_blocks_blocker_id_desc
    ON user_blocks (blocker_id, id DESC);

CREATE INDEX ix_user_blocks_pair
    ON user_blocks (blocker_id, blocked_id);

CREATE TABLE outbox_events (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    event_id VARCHAR(64) NOT NULL UNIQUE,
    event_type VARCHAR(128) NOT NULL,
    payload_version INT NOT NULL DEFAULT 1,
    aggregate_type VARCHAR(64) NOT NULL,
    aggregate_id VARCHAR(64) NOT NULL,
    payload_json JSONB NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    claimed_by VARCHAR(128) NULL,
    claim_started_at TIMESTAMPTZ NULL,
    attempt_count INT NOT NULL DEFAULT 0,
    next_retry_at TIMESTAMPTZ NULL,
    last_error TEXT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at TIMESTAMPTZ NULL,
    CHECK (payload_version > 0),
    CHECK (status IN ('PENDING', 'CLAIMING', 'PUBLISHED', 'FAILED', 'DEAD')),
    CHECK (status = 'CLAIMING' OR (claimed_by IS NULL AND claim_started_at IS NULL)),
    CHECK (status <> 'CLAIMING' OR (claimed_by IS NOT NULL AND claim_started_at IS NOT NULL)),
    CHECK (attempt_count >= 0),
    CHECK (published_at IS NULL OR published_at >= occurred_at)
);

CREATE INDEX ix_outbox_events_status_next_retry_at_id
    ON outbox_events (status, next_retry_at, id);

CREATE INDEX ix_outbox_events_claim_started_at
    ON outbox_events (claim_started_at)
    WHERE status = 'CLAIMING';

CREATE INDEX ix_outbox_events_aggregate_occurred_at
    ON outbox_events (aggregate_type, aggregate_id, occurred_at);

COMMIT;
