BEGIN;

CREATE TABLE auth_accounts (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NULL,
    email VARCHAR(254) NOT NULL,
    email_normalized VARCHAR(254) NOT NULL,
    status VARCHAR(32) NOT NULL,
    session_version BIGINT NOT NULL DEFAULT 1,
    principal_version BIGINT NOT NULL DEFAULT 1,
    registration_nickname VARCHAR(64) NULL,
    pending_expires_at TIMESTAMPTZ NULL,
    locked_until TIMESTAMPTZ NULL,
    lock_reason VARCHAR(64) NULL,
    last_login_at TIMESTAMPTZ NULL,
    last_login_ip INET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (status IN ('PENDING_PROFILE', 'ACTIVE', 'DISABLED', 'BANNED', 'EXPIRED')),
    CHECK (session_version > 0),
    CHECK (principal_version > 0),
    CHECK (status <> 'ACTIVE' OR user_id IS NOT NULL)
);

CREATE UNIQUE INDEX ux_auth_accounts_user_id
    ON auth_accounts (user_id)
    WHERE user_id IS NOT NULL;

CREATE UNIQUE INDEX ux_auth_accounts_email_normalized_occupied
    ON auth_accounts (email_normalized)
    WHERE status IN ('PENDING_PROFILE', 'ACTIVE', 'DISABLED', 'BANNED');

CREATE INDEX idx_auth_accounts_email_normalized
    ON auth_accounts (email_normalized);

CREATE INDEX idx_auth_accounts_status
    ON auth_accounts (status);

CREATE INDEX idx_auth_accounts_pending_expires_at
    ON auth_accounts (pending_expires_at);

CREATE INDEX idx_auth_accounts_locked_until
    ON auth_accounts (locked_until);

CREATE TABLE auth_password_credentials (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    account_id BIGINT NOT NULL UNIQUE REFERENCES auth_accounts (id),
    password_hash VARCHAR(255) NOT NULL,
    credential_version BIGINT NOT NULL DEFAULT 1,
    password_updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (credential_version > 0)
);

CREATE TABLE auth_account_roles (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    account_id BIGINT NOT NULL REFERENCES auth_accounts (id),
    role VARCHAR(64) NOT NULL,
    granted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    granted_by_account_id BIGINT NULL REFERENCES auth_accounts (id),
    grant_reason VARCHAR(128) NULL,
    revoked_at TIMESTAMPTZ NULL,
    revoked_by_account_id BIGINT NULL REFERENCES auth_accounts (id),
    revoke_reason VARCHAR(128) NULL,
    CHECK (revoked_at IS NULL OR revoked_at >= granted_at)
);

CREATE UNIQUE INDEX ux_auth_account_roles_active_role
    ON auth_account_roles (account_id, role)
    WHERE revoked_at IS NULL;

CREATE INDEX idx_auth_account_roles_account_revoked_at
    ON auth_account_roles (account_id, revoked_at);

CREATE TABLE auth_refresh_sessions (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    session_id VARCHAR(64) NOT NULL UNIQUE,
    account_id BIGINT NOT NULL REFERENCES auth_accounts (id),
    current_token_id VARCHAR(64) NOT NULL UNIQUE,
    current_token_hash VARCHAR(128) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_used_at TIMESTAMPTZ NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ NULL,
    revoked_reason VARCHAR(64) NULL,
    revoked_by_account_id BIGINT NULL REFERENCES auth_accounts (id),
    last_access_jti VARCHAR(128) NULL,
    user_agent TEXT NULL,
    device_label VARCHAR(128) NULL,
    created_ip INET NULL,
    last_seen_ip INET NULL,
    CHECK (expires_at > created_at),
    CHECK (revoked_at IS NULL OR revoked_at >= created_at)
);

CREATE INDEX idx_auth_refresh_sessions_account_revoked_expires
    ON auth_refresh_sessions (account_id, revoked_at, expires_at);

CREATE INDEX idx_auth_refresh_sessions_account_expires
    ON auth_refresh_sessions (account_id, expires_at);

CREATE TABLE auth_used_refresh_tokens (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    session_id VARCHAR(64) NOT NULL REFERENCES auth_refresh_sessions (session_id),
    account_id BIGINT NOT NULL REFERENCES auth_accounts (id),
    token_id VARCHAR(64) NOT NULL UNIQUE,
    token_hash VARCHAR(128) NOT NULL UNIQUE,
    used_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL,
    CHECK (expires_at >= used_at)
);

CREATE INDEX idx_auth_used_refresh_tokens_session_token_id
    ON auth_used_refresh_tokens (session_id, token_id);

CREATE INDEX idx_auth_used_refresh_tokens_expires_at
    ON auth_used_refresh_tokens (expires_at);

CREATE TABLE auth_security_operations (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    operation_id VARCHAR(64) NOT NULL UNIQUE,
    type VARCHAR(64) NOT NULL,
    account_id BIGINT NOT NULL REFERENCES auth_accounts (id),
    target_session_id VARCHAR(64) NULL REFERENCES auth_refresh_sessions (session_id),
    actor_type VARCHAR(32) NOT NULL,
    actor_account_id BIGINT NULL REFERENCES auth_accounts (id),
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    retry_after_seconds INT NULL,
    attempt_count INT NOT NULL DEFAULT 0,
    next_retry_at TIMESTAMPTZ NULL,
    last_error_code VARCHAR(64) NULL,
    last_error_message TEXT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMPTZ NULL,
    CHECK (actor_type IN ('user', 'admin', 'system', 'service')),
    CHECK (status IN ('PENDING', 'SUCCEEDED', 'FAILED')),
    CHECK (retry_after_seconds IS NULL OR retry_after_seconds > 0),
    CHECK (attempt_count >= 0),
    CHECK (completed_at IS NULL OR completed_at >= created_at)
);

CREATE INDEX idx_auth_security_operations_account_created_at
    ON auth_security_operations (account_id, created_at DESC);

CREATE INDEX idx_auth_security_operations_status_next_retry_at_id
    ON auth_security_operations (status, next_retry_at, id);

CREATE TABLE auth_audit_logs (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    event_type VARCHAR(64) NOT NULL,
    account_id BIGINT NULL REFERENCES auth_accounts (id),
    user_id BIGINT NULL,
    operator_account_id BIGINT NULL REFERENCES auth_accounts (id),
    session_id VARCHAR(64) NULL,
    request_id VARCHAR(64) NULL,
    trace_id VARCHAR(64) NULL,
    ip INET NULL,
    ip_hash VARCHAR(128) NULL,
    user_agent TEXT NULL,
    user_agent_hash VARCHAR(128) NULL,
    metadata_json JSONB NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_auth_audit_logs_account_created_at
    ON auth_audit_logs (account_id, created_at DESC);

CREATE INDEX idx_auth_audit_logs_event_type_created_at
    ON auth_audit_logs (event_type, created_at DESC);

CREATE INDEX idx_auth_audit_logs_request_id
    ON auth_audit_logs (request_id);

CREATE INDEX idx_auth_audit_logs_ip_hash_created_at
    ON auth_audit_logs (ip_hash, created_at DESC);

CREATE TABLE auth_outbox_events (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    event_id VARCHAR(64) NOT NULL UNIQUE,
    event_type VARCHAR(128) NOT NULL,
    event_version INT NOT NULL DEFAULT 1,
    aggregate_type VARCHAR(64) NOT NULL,
    aggregate_id VARCHAR(64) NOT NULL,
    payload_json JSONB NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    attempt_count INT NOT NULL DEFAULT 0,
    next_retry_at TIMESTAMPTZ NULL,
    last_error TEXT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at TIMESTAMPTZ NULL,
    CHECK (event_version > 0),
    CHECK (status IN ('PENDING', 'PUBLISHED', 'FAILED')),
    CHECK (attempt_count >= 0),
    CHECK (published_at IS NULL OR published_at >= occurred_at)
);

CREATE INDEX idx_auth_outbox_events_status_next_retry_at_id
    ON auth_outbox_events (status, next_retry_at, id);

CREATE INDEX idx_auth_outbox_events_aggregate_occurred_at
    ON auth_outbox_events (aggregate_type, aggregate_id, occurred_at);

COMMIT;
