BEGIN;

CREATE TABLE notification_campaign (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    source_event_id VARCHAR(128) NOT NULL,
    campaign_type VARCHAR(64) NOT NULL,
    author_id BIGINT NOT NULL,
    post_id BIGINT NOT NULL,
    object_type VARCHAR(64) NOT NULL,
    object_id BIGINT NOT NULL,
    audience_class VARCHAR(32) NOT NULL,
    audience_active_since TIMESTAMPTZ NULL,
    audience_estimate BIGINT NULL,
    title VARCHAR(256) NOT NULL,
    excerpt VARCHAR(512) NOT NULL DEFAULT '',
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    published_at TIMESTAMPTZ NOT NULL,
    status VARCHAR(64) NOT NULL,
    last_error_code VARCHAR(128) NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (source_event_id <> ''),
    CHECK (campaign_type <> ''),
    CHECK (author_id > 0),
    CHECK (post_id > 0),
    CHECK (object_type <> ''),
    CHECK (object_id > 0),
    CHECK (audience_class IN ('HOT', 'WARM', 'COLD', 'ALL')),
    CHECK (audience_estimate IS NULL OR audience_estimate >= 0),
    CHECK (title <> ''),
    CHECK (status IN ('PLANNED', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELED'))
);

CREATE UNIQUE INDEX ux_notification_campaign_source_event_id
    ON notification_campaign (source_event_id);

CREATE INDEX ix_notification_campaign_status_created_at
    ON notification_campaign (status, created_at);

CREATE TABLE notification_campaign_shard (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    campaign_id BIGINT NOT NULL REFERENCES notification_campaign (id),
    audience_class VARCHAR(32) NOT NULL,
    audience_active_since TIMESTAMPTZ NULL,
    follower_cursor VARCHAR(256) NOT NULL DEFAULT '',
    next_follower_cursor VARCHAR(256) NOT NULL DEFAULT '',
    shard_size BIGINT NULL,
    processed_count BIGINT NOT NULL DEFAULT 0,
    success_count BIGINT NOT NULL DEFAULT 0,
    skipped_count BIGINT NOT NULL DEFAULT 0,
    failed_count BIGINT NOT NULL DEFAULT 0,
    status VARCHAR(64) NOT NULL,
    claimed_by VARCHAR(128) NOT NULL DEFAULT '',
    claimed_at TIMESTAMPTZ NULL,
    claim_deadline_at TIMESTAMPTZ NULL,
    next_retry_at TIMESTAMPTZ NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    last_error_code VARCHAR(128) NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (shard_size IS NULL OR shard_size >= 0),
    CHECK (processed_count >= 0),
    CHECK (success_count >= 0),
    CHECK (skipped_count >= 0),
    CHECK (failed_count >= 0),
    CHECK (attempt_count >= 0),
    CHECK (processed_count >= success_count + skipped_count + failed_count),
    CHECK (audience_class IN ('HOT', 'WARM', 'COLD', 'ALL')),
    CHECK (status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED'))
);

CREATE INDEX ix_notification_campaign_shard_campaign_id
    ON notification_campaign_shard (campaign_id, id);

CREATE INDEX ix_notification_campaign_shard_claim
    ON notification_campaign_shard (status, next_retry_at, id)
    WHERE status IN ('PENDING', 'FAILED');

ALTER TABLE notification_delivery
    ADD CONSTRAINT fk_notification_delivery_campaign
    FOREIGN KEY (campaign_id) REFERENCES notification_campaign (id);

COMMIT;
