BEGIN;

CREATE TABLE notifications (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    public_id VARCHAR(32) NOT NULL,
    recipient_id BIGINT NOT NULL,
    actor_id BIGINT NULL,
    category VARCHAR(32) NOT NULL,
    notification_type VARCHAR(64) NOT NULL,
    event_code VARCHAR(128) NOT NULL,
    importance VARCHAR(16) NOT NULL DEFAULT 'NORMAL',
    target_type VARCHAR(64) NOT NULL,
    target_id VARCHAR(128) NOT NULL,
    source_event_id VARCHAR(128) NOT NULL,
    dedupe_key VARCHAR(256) NOT NULL,
    group_key VARCHAR(256) NOT NULL,
    title VARCHAR(200) NOT NULL,
    content VARCHAR(500) NOT NULL,
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    read_at TIMESTAMPTZ NULL,
    archived_at TIMESTAMPTZ NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (public_id <> ''),
    CHECK (recipient_id > 0),
    CHECK (actor_id IS NULL OR actor_id > 0),
    CHECK (category IN ('INTERACTION', 'CONTENT', 'SOCIAL', 'SYSTEM', 'SECURITY')),
    CHECK (notification_type IN ('POST_LIKED', 'POST_COMMENTED', 'COMMENT_REPLIED', 'USER_FOLLOWED', 'POST_PUBLISHED_BY_FOLLOWING', 'POST_PUBLISHED_DIGEST', 'SYSTEM_ANNOUNCEMENT', 'SECURITY_ALERT')),
    CHECK (importance IN ('NORMAL', 'HIGH', 'CRITICAL')),
    CHECK (target_type <> ''),
    CHECK (target_id <> ''),
    CHECK (source_event_id <> ''),
    CHECK (dedupe_key <> ''),
    CHECK (group_key <> ''),
    CHECK (title <> ''),
    CHECK (content <> ''),
    CHECK (read_at IS NULL OR is_read),
    CHECK (expires_at IS NULL OR expires_at > created_at)
);

CREATE UNIQUE INDEX ux_notifications_public_id
    ON notifications (public_id);

CREATE UNIQUE INDEX ux_notifications_source_event_id
    ON notifications (source_event_id);

CREATE UNIQUE INDEX ux_notifications_recipient_dedupe_key
    ON notifications (recipient_id, dedupe_key);

CREATE INDEX ix_notifications_recipient_created_at
    ON notifications (recipient_id, created_at DESC, id DESC);

CREATE INDEX ix_notifications_recipient_is_read_created_at
    ON notifications (recipient_id, is_read, created_at DESC, id DESC);

CREATE INDEX ix_notifications_group_key
    ON notifications (recipient_id, group_key, created_at DESC, id DESC);

CREATE INDEX ix_notifications_expires_at
    ON notifications (expires_at)
    WHERE expires_at IS NOT NULL;

CREATE TABLE notification_group_state (
    recipient_id BIGINT NOT NULL,
    group_key VARCHAR(256) NOT NULL,
    notification_type VARCHAR(64) NOT NULL,
    category VARCHAR(32) NOT NULL,
    target_type VARCHAR(64) NOT NULL,
    target_id VARCHAR(128) NOT NULL,
    latest_notification_id BIGINT NOT NULL REFERENCES notifications (id),
    total_count BIGINT NOT NULL DEFAULT 0,
    unread_count BIGINT NOT NULL DEFAULT 0,
    latest_time TIMESTAMPTZ NOT NULL,
    latest_content VARCHAR(500) NOT NULL,
    latest_actor_ids BIGINT[] NOT NULL DEFAULT '{}',
    aggregated_content JSONB NOT NULL DEFAULT '{}'::jsonb,
    repair_required BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (recipient_id, group_key),
    CHECK (recipient_id > 0),
    CHECK (group_key <> ''),
    CHECK (notification_type IN ('POST_LIKED', 'POST_COMMENTED', 'COMMENT_REPLIED', 'USER_FOLLOWED', 'POST_PUBLISHED_BY_FOLLOWING', 'POST_PUBLISHED_DIGEST', 'SYSTEM_ANNOUNCEMENT', 'SECURITY_ALERT')),
    CHECK (category IN ('INTERACTION', 'CONTENT', 'SOCIAL', 'SYSTEM', 'SECURITY')),
    CHECK (target_type <> ''),
    CHECK (target_id <> ''),
    CHECK (total_count >= 0),
    CHECK (unread_count >= 0),
    CHECK (unread_count <= total_count),
    CHECK (latest_content <> '')
);

CREATE INDEX ix_notification_group_state_recipient_latest_time
    ON notification_group_state (recipient_id, latest_time DESC, group_key DESC);

CREATE INDEX ix_notification_group_state_repair_required
    ON notification_group_state (recipient_id)
    WHERE repair_required;

CREATE TABLE consumed_events (
    event_id VARCHAR(128) NOT NULL PRIMARY KEY,
    event_type VARCHAR(128) NOT NULL,
    routing_key VARCHAR(128) NOT NULL,
    consumer_name VARCHAR(128) NOT NULL,
    payload_hash VARCHAR(128) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PROCESSING',
    consumed_at TIMESTAMPTZ NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    last_error_class VARCHAR(64) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (event_id <> ''),
    CHECK (event_type <> ''),
    CHECK (routing_key <> ''),
    CHECK (consumer_name <> ''),
    CHECK (payload_hash <> ''),
    CHECK (status IN ('PROCESSING', 'CONSUMED', 'FAILED', 'DEAD')),
    CHECK (expires_at > created_at)
);

CREATE INDEX ix_consumed_events_expires_at
    ON consumed_events (expires_at);

CREATE INDEX ix_consumed_events_status_updated_at
    ON consumed_events (status, updated_at);

COMMIT;
