BEGIN;

CREATE TABLE notification_user_preference (
    user_id BIGINT NOT NULL,
    notification_type VARCHAR(64) NOT NULL,
    channel VARCHAR(32) NOT NULL,
    enabled BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, notification_type, channel),
    CHECK (user_id > 0),
    CHECK (notification_type <> ''),
    CHECK (channel IN ('IN_APP', 'WEBSOCKET', 'EMAIL', 'SMS'))
);

CREATE TABLE notification_user_dnd (
    user_id BIGINT PRIMARY KEY,
    enabled BOOLEAN NOT NULL DEFAULT FALSE,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    timezone VARCHAR(64) NOT NULL,
    categories VARCHAR(64)[] NOT NULL DEFAULT '{}',
    channels VARCHAR(32)[] NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (user_id > 0),
    CHECK (timezone <> ''),
    CHECK (start_time <> end_time)
);

CREATE TABLE notification_author_subscription (
    user_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    level VARCHAR(32) NOT NULL,
    in_app_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    websocket_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    email_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    digest_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, author_id),
    CHECK (user_id > 0),
    CHECK (author_id > 0),
    CHECK (level IN ('ALL', 'DIGEST_ONLY', 'MUTED'))
);

CREATE TABLE notification_delivery (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    public_id VARCHAR(32) NOT NULL,
    recipient_id BIGINT NOT NULL,
    notification_id BIGINT NULL REFERENCES notifications (id),
    campaign_id BIGINT NULL,
    channel VARCHAR(32) NOT NULL,
    notification_type VARCHAR(64) NOT NULL,
    status VARCHAR(64) NOT NULL,
    provider VARCHAR(64) NOT NULL DEFAULT '',
    dedupe_key VARCHAR(256) NOT NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    last_error_code VARCHAR(128) NOT NULL DEFAULT '',
    next_retry_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (recipient_id > 0),
    CHECK (public_id <> ''),
    CHECK (channel IN ('IN_APP', 'WEBSOCKET', 'EMAIL', 'SMS')),
    CHECK (status IN ('PLANNED', 'INBOX_CREATED', 'WEBSOCKET_PENDING', 'WEBSOCKET_DISPATCHED', 'DIGEST_PENDING', 'DIGEST_DELIVERED', 'SKIPPED', 'FAILED')),
    CHECK (attempt_count >= 0),
    CHECK (dedupe_key <> '')
);

CREATE UNIQUE INDEX ux_notification_delivery_public_id
    ON notification_delivery (public_id);

CREATE UNIQUE INDEX ux_notification_delivery_dedupe_key
    ON notification_delivery (dedupe_key);

CREATE INDEX ix_notification_delivery_recipient_created_at
    ON notification_delivery (recipient_id, created_at DESC, public_id DESC);

CREATE INDEX ix_notification_delivery_status_next_retry_at
    ON notification_delivery (status, next_retry_at)
    WHERE status IN ('WEBSOCKET_PENDING', 'DIGEST_PENDING', 'FAILED');

COMMIT;
