#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

required_dirs=(
  "services/zhicore-gateway/cmd/server"
  "services/zhicore-gateway/internal/gateway"
  "services/zhicore-gateway/api/http"
  "services/zhicore-gateway/configs"
  "services/zhicore-gateway/migrations"
  "services/zhicore-auth/cmd/server"
  "services/zhicore-auth/internal/auth"
  "services/zhicore-auth/api/http"
  "services/zhicore-auth/configs"
  "services/zhicore-auth/migrations"
  "services/zhicore-user/cmd/server"
  "services/zhicore-user/internal/user"
  "services/zhicore-user/api/http"
  "services/zhicore-user/configs"
  "services/zhicore-user/migrations"
  "services/zhicore-content/cmd/server"
  "services/zhicore-content/internal/content"
  "services/zhicore-content/api/http"
  "services/zhicore-content/configs"
  "services/zhicore-content/migrations"
  "services/zhicore-comment/cmd/server"
  "services/zhicore-comment/internal/comment"
  "services/zhicore-comment/api/http"
  "services/zhicore-comment/configs"
  "services/zhicore-comment/migrations"
  "services/zhicore-message/cmd/server"
  "services/zhicore-message/internal/message"
  "services/zhicore-message/api/http"
  "services/zhicore-message/configs"
  "services/zhicore-message/migrations"
  "services/zhicore-notification/cmd/server"
  "services/zhicore-notification/internal/notification"
  "services/zhicore-notification/api/http"
  "services/zhicore-notification/configs"
  "services/zhicore-notification/migrations"
  "services/zhicore-search/cmd/server"
  "services/zhicore-search/internal/search"
  "services/zhicore-search/api/http"
  "services/zhicore-search/configs"
  "services/zhicore-search/migrations"
  "services/zhicore-ranking/cmd/server"
  "services/zhicore-ranking/internal/ranking"
  "services/zhicore-ranking/api/http"
  "services/zhicore-ranking/configs"
  "services/zhicore-ranking/migrations"
  "services/zhicore-admin/cmd/server"
  "services/zhicore-admin/internal/admin"
  "services/zhicore-admin/api/http"
  "services/zhicore-admin/configs"
  "services/zhicore-admin/migrations"
  "services/zhicore-file/cmd/server"
  "services/zhicore-file/internal/file"
  "services/zhicore-file/api/http"
  "services/zhicore-file/configs"
  "services/zhicore-file/migrations"
  "services/zhicore-id-generator/cmd/server"
  "services/zhicore-id-generator/internal/idgenerator"
  "services/zhicore-id-generator/api/http"
  "services/zhicore-id-generator/configs"
  "services/zhicore-id-generator/migrations"
  "services/zhicore-ops/cmd/server"
  "services/zhicore-ops/internal/ops"
  "services/zhicore-ops/api/http"
  "services/zhicore-ops/configs"
  "services/zhicore-ops/migrations"
  "libs/kit/httpapi"
  "libs/kit/auth"
  "libs/kit/config"
  "libs/kit/observability"
  "libs/kit/postgres"
  "libs/kit/redis"
  "libs/kit/mongo"
  "libs/kit/rabbitmq"
  "libs/kit/es"
  "libs/contracts/events"
  "libs/contracts/events/auth"
  "libs/contracts/clients"
  "libs/contracts/clients/auth"
  "deploy/docker"
  "deploy/k8s"
  "docs/architecture"
  "docs/architecture/module"
  "docs/architecture/module/auth"
  "docs/architecture/services"
  "docs/architecture/services/_overview"
  "docs/architecture/services/gateway"
  "docs/architecture/services/auth"
  "docs/architecture/services/user"
  "docs/architecture/services/content"
  "docs/architecture/services/comment"
  "docs/architecture/services/message"
  "docs/architecture/services/notification"
  "docs/architecture/services/search"
  "docs/architecture/services/ranking"
  "docs/architecture/services/admin"
  "docs/architecture/services/file"
  "docs/architecture/services/id-generator"
  "docs/architecture/services/ops"
  "docs/contracts"
  "docs/migration"
  "docs/reviews"
  "docs/todos/debt"
  ".githooks"
  "harness/policies"
  "tests/architecture"
  "tests/system/http"
  "tests/runtime"
  "tests/testkit"
)

for dir in "${required_dirs[@]}"; do
  if [[ ! -d "$ROOT/$dir" ]]; then
    echo "missing directory: $dir" >&2
    exit 1
  fi
done

required_files=(
  "AGENTS.md"
  "CLAUDE.md"
  "README.md"
  "go.work"
  "libs/contracts/go.mod"
  "libs/contracts/clients/auth/README.md"
  "libs/contracts/events/auth/README.md"
  "libs/kit/go.mod"
  "services/zhicore-gateway/go.mod"
  "services/zhicore-auth/go.mod"
  "services/zhicore-auth/README.md"
  "services/zhicore-auth/api/http/README.md"
  "services/zhicore-auth/internal/auth/doc.go"
  "services/zhicore-user/go.mod"
  "services/zhicore-content/go.mod"
  "services/zhicore-comment/go.mod"
  "services/zhicore-message/go.mod"
  "services/zhicore-notification/go.mod"
  "services/zhicore-search/go.mod"
  "services/zhicore-ranking/go.mod"
  "services/zhicore-admin/go.mod"
  "services/zhicore-file/go.mod"
  "services/zhicore-id-generator/go.mod"
  "services/zhicore-ops/go.mod"
  "docs/README.md"
  "docs/documentation-rules.md"
  "docs/architecture/repository-layout.md"
  "docs/architecture/go-service-design.md"
  "docs/architecture/configuration.md"
  "docs/architecture/observability.md"
  "docs/architecture/security.md"
  "docs/architecture/migrations.md"
  "docs/architecture/testing.md"
  "docs/architecture/error-handling.md"
  "docs/architecture/runtime-operations.md"
  "docs/architecture/service-boundaries.md"
  "docs/architecture/id-strategy.md"
  "docs/architecture/module/README.md"
  "docs/architecture/module/auth/README.md"
  "docs/architecture/module/auth/api.md"
  "docs/architecture/module/auth/service.md"
  "docs/architecture/module/auth/domain.md"
  "docs/architecture/module/auth/ports.md"
  "docs/architecture/module/auth/data-events.md"
  "docs/architecture/services/README.md"
  "docs/architecture/services/_overview/service-design.drawio"
  "docs/architecture/services/_overview/service-design.overview.png"
  "docs/architecture/services/gateway/README.md"
  "docs/architecture/services/gateway/service-design.gateway.png"
  "docs/architecture/services/gateway/service-detail.drawio"
  "docs/architecture/services/gateway/service-detail.png"
  "docs/architecture/services/auth/README.md"
  "docs/architecture/services/user/README.md"
  "docs/architecture/services/user/service-design.user.png"
  "docs/architecture/services/user/service-detail.drawio"
  "docs/architecture/services/user/service-detail.png"
  "docs/architecture/services/content/README.md"
  "docs/architecture/services/content/service-design.content.png"
  "docs/architecture/services/content/service-detail.drawio"
  "docs/architecture/services/content/service-detail.png"
  "docs/architecture/services/comment/README.md"
  "docs/architecture/services/comment/service-design.comment.png"
  "docs/architecture/services/comment/service-detail.drawio"
  "docs/architecture/services/comment/service-detail.png"
  "docs/architecture/services/message/README.md"
  "docs/architecture/services/message/service-design.message.png"
  "docs/architecture/services/message/service-detail.drawio"
  "docs/architecture/services/message/service-detail.png"
  "docs/architecture/services/notification/README.md"
  "docs/architecture/services/notification/service-design.notification.png"
  "docs/architecture/services/notification/service-detail.drawio"
  "docs/architecture/services/notification/service-detail.png"
  "docs/architecture/services/search/README.md"
  "docs/architecture/services/search/service-design.search.png"
  "docs/architecture/services/search/service-detail.drawio"
  "docs/architecture/services/search/service-detail.png"
  "docs/architecture/services/ranking/README.md"
  "docs/architecture/services/ranking/service-design.ranking.png"
  "docs/architecture/services/ranking/service-detail.drawio"
  "docs/architecture/services/ranking/service-detail.png"
  "docs/architecture/services/admin/README.md"
  "docs/architecture/services/admin/service-design.admin.png"
  "docs/architecture/services/admin/service-detail.drawio"
  "docs/architecture/services/admin/service-detail.png"
  "docs/architecture/services/file/README.md"
  "docs/architecture/services/file/service-design.file.png"
  "docs/architecture/services/file/service-detail.drawio"
  "docs/architecture/services/file/service-detail.png"
  "docs/architecture/services/id-generator/README.md"
  "docs/architecture/services/id-generator/service-design.id-generator.png"
  "docs/architecture/services/id-generator/service-detail.drawio"
  "docs/architecture/services/id-generator/service-detail.png"
  "docs/architecture/services/ops/README.md"
  "docs/architecture/services/ops/service-design.ops.png"
  "docs/architecture/services/ops/service-detail.drawio"
  "docs/architecture/services/ops/service-detail.png"
  "docs/contracts/README.md"
  "docs/contracts/http.md"
  "docs/contracts/http-schema-template.md"
  "docs/contracts/errors.md"
  "docs/contracts/error-codes.md"
  "docs/contracts/data-types.md"
  "docs/contracts/pagination.md"
  "docs/contracts/events.md"
  "docs/migration/README.md"
  "docs/migration/service-migration-workflow.md"
  "docs/reviews/README.md"
  "docs/reviews/done-definition.md"
  "docs/reviews/commit-message.md"
  "docs/reviews/quality-gates.md"
  "docs/reviews/backend/README.md"
  ".githooks/README.md"
  ".githooks/commit-msg"
  "harness/policies/commit-message.json"
  "scripts/check-commit-message.sh"
  "scripts/install-githooks.sh"
)

for file in "${required_files[@]}"; do
  if [[ ! -e "$ROOT/$file" ]]; then
    echo "missing file: $file" >&2
    exit 1
  fi
done

required_executables=(
  ".githooks/commit-msg"
  "scripts/check-commit-message.sh"
  "scripts/install-githooks.sh"
)

for file in "${required_executables[@]}"; do
  if [[ ! -x "$ROOT/$file" ]]; then
    echo "file must be executable: $file" >&2
    exit 1
  fi
done

if [[ ! -L "$ROOT/CLAUDE.md" ]]; then
  echo "CLAUDE.md must be a symlink to AGENTS.md" >&2
  exit 1
fi

if [[ "$(readlink "$ROOT/CLAUDE.md")" != "AGENTS.md" ]]; then
  echo "CLAUDE.md must point to AGENTS.md" >&2
  exit 1
fi

if [[ -e "$ROOT/go.mod" ]]; then
  echo "root go.mod is not allowed; use go.work plus per-service modules" >&2
  exit 1
fi

if [[ -d "$ROOT/cmd" || -d "$ROOT/internal" ]]; then
  echo "root cmd/ and internal/ are not allowed; use services/<service> and libs/" >&2
  exit 1
fi

echo "structure ok"
